# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the "main" branch
  push:
    branches: [ "main" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This is the first job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3

    - name: Change permissions of Jest command
      run: chmod +x node_modules/.bin/jest

    
    - name: Use Node.js
      uses: actions/setup-node@v3
      
    - name: Install dependencies
      run: npm install

    - name: Run Test
      run: npm test


# Create a second job for deployment
  deploy:
    runs-on: windows-latest
    needs: [build]
    name: 'Deploy to Netlify'
    steps:
      - uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY }}
          NETLIFY_DEPLOY_TO_PROD: true
